#!/bin/bash

# enable nbserverproxy
jupyter serverextension enable --sys-prefix nbserverproxy

# install the dash server extension so that
# dash launches at startup
mv dashserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/

# enable bokeh extension
jupyter serverextension enable --sys-prefix dashserverextension
